/**
 * Helpers to load generated GTFS static data.
 * These files are generated by scripts/build-gtfs.ts at build time.
 */

import * as fs from "fs";
import * as path from "path";

export interface Station {
  id: string;
  name: string;
  slug: string;
  lat: number;
  lon: number;
  childStopIds: string[];
}

export interface Route {
  id: string;
  shortName: string;
  longName: string;
  color: string;
  textColor: string;
  slug: string;
}

const DATA_DIR = path.join(process.cwd(), "src", "data", "gtfs");

function loadJson<T>(filename: string): T {
  const filepath = path.join(DATA_DIR, filename);
  const raw = fs.readFileSync(filepath, "utf-8");
  return JSON.parse(raw) as T;
}

let _stations: Station[] | null = null;
let _routes: Route[] | null = null;
let _stationRoutes: Record<string, string[]> | null = null;
let _routeStations: Record<string, string[]> | null = null;

export function getStations(): Station[] {
  if (!_stations) _stations = loadJson<Station[]>("stations.json");
  return _stations;
}

export function getRoutes(): Route[] {
  if (!_routes) _routes = loadJson<Route[]>("routes.json");
  return _routes;
}

export function getStationRoutes(): Record<string, string[]> {
  if (!_stationRoutes)
    _stationRoutes = loadJson<Record<string, string[]>>("stationRoutes.json");
  return _stationRoutes;
}

export function getRouteStations(): Record<string, string[]> {
  if (!_routeStations)
    _routeStations = loadJson<Record<string, string[]>>("routeStations.json");
  return _routeStations;
}

export function getStationBySlug(slug: string): Station | undefined {
  return getStations().find((s) => s.slug === slug);
}

export function getRouteBySlug(slug: string): Route | undefined {
  return getRoutes().find((r) => r.slug === slug);
}

export function getRouteById(id: string): Route | undefined {
  return getRoutes().find((r) => r.id === id);
}

export function getRoutesForStation(stationId: string): Route[] {
  const routeIds = getStationRoutes()[stationId] || [];
  return routeIds.map(getRouteById).filter(Boolean) as Route[];
}

export function getStationsForRoute(routeId: string): Station[] {
  const stationIds = getRouteStations()[routeId] || [];
  const stations = getStations();
  return stationIds
    .map((id) => stations.find((s) => s.id === id))
    .filter(Boolean) as Station[];
}
